site_name: Asynchronous k-mer Counting
site_url: https://souvadra.github.io/dakc
theme:
  name: material

nav:
  - Home: index.md
  - DAKC: dakc.md
  - Analytical Model: model.md
  - PakMan*: pkm.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mdx_math
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js